### ISSUE TITLE
I can't create service in Android 30

### ISSUE THREAD

**Issue by BritnessDev** [BritnessDev/Android-Service-Example#1]
Everything is going well in API 26.
But anything isn't working in API 30.
Please let's solve this problem.

**Comment by thsWebstorm03** [comment]
To create a foreground service, you need to follow these steps:

Create a service class that extends the Service class.
In the onCreate() method of your service, start the service as a foreground service using the startForeground() method. This method requires a notification that will be shown to the user.
Implement the necessary functionality of your service in the onStartCommand() method.
Stop the foreground service when it is no longer needed using the stopForeground() method.

**Comment by BritnessDev** [comment]
> To create a foreground service, you need to follow these steps:
> 
> Create a service class that extends the Service class. In the onCreate() method of your service, start the service as a foreground service using the startForeground() method. This method requires a notification that will be shown to the user. Implement the necessary functionality of your service in the onStartCommand() method. Stop the foreground service when it is no longer needed using the stopForeground() method.

Great! Thanks. It works for me!
Really thanks for your help.
